### ISSUE TITLE
Display number of remaining threats in dialog

### ISSUE THREAD

**Issue by garethbradley** [mike-goodwin/owasp-threat-dragon-core#1]
When selecting an item in the threat model, then "suggest threats for the selected element", a dialog pops up with a suggest threat. Accepting or Ignoring the dialog may cause further threats to show up. It would be useful if the title of the dialog could show a count. E.g. "Add this threat? (1 / 4)"

**Comment by mike-goodwin** [comment]
fixed in commit b8efc67
