### ISSUE TITLE
Failed test 'should duplicate a boundary element'

### ISSUE THREAD

**Issue by jgadsden** [mike-goodwin/owasp-threat-dragon-core#114]
This now fails, and this is associated with an error when duplicating a boundary in the diagram edit view.
This is a corner case, in practice it is very rare that a boundary is duplicated, but the test is quite rightly picking this up.

**Comment by andk123** [comment]
Interesting, do you want me to look into that instead?

**Comment by jgadsden** [comment]
Yes, thanks - I had a quick look and it may be centred round function duplicateElement()
