### ISSUE TITLE
Command line sync utility linking TD file to Jira Epic

### ISSUE THREAD

**Issue by jcoupal** [mike-goodwin/owasp-threat-dragon-core#118]
My company built a utility that helps us out a lot with Threat Modeling - we have a 2-way sync utility that pushes open (non-mitigated) vulnerabilities into a a named Jira Epic as a simpler way to build backlog for our dev team. Once closed in Jira, the items get marked as closed in TD.

[threat-mvp-master.zip](https://github.com/mike-goodwin/owasp-threat-dragon-desktop/files/4658557/threat-mvp-master.zip)

**Comment by jcoupal** [comment]
![itx logo](https://user-images.githubusercontent.com/56204742/82733770-473edc80-9ce4-11ea-971e-9f09b301eb34.png)

Sure, here it is.

**Comment by jgadsden** [comment]
Many thanks @jcoupal for the logo. Will update the OWASP project page when we wrok out where in the repo the utility should be stored.
We are having discussions as to where your utility should sit in the repo structure ... it may have its own repo under a Threat Dragon github organisation, or may go into a utility directory in this repo. Not sure which one ...

**Comment by jgadsden** [comment]
Migrated to new issue in the OWASP area repo : https://github.com/OWASP/threat-dragon-core/issues/17
