### ISSUE TITLE
The problem is how do you debug and run the core part in your comuter?

### ISSUE THREAD

**Issue by ZhangK123** [mike-goodwin/owasp-threat-dragon-core#121]
I want to add some new funtions in my computer. The problem is how do you debug and run the core part in your comuter?

Is this core-part must run on the   Web application?

**Comment by jgadsden** [comment]
Hello @ZhangK123 - you raise a very good point, in that the development for both TD webapp and TD desktop rely on the common core functions/package. I have raised an issue in the OWASP repo for this:

https://github.com/OWASP/threat-dragon-core/issues/28

and I will put some notes in there on how I run and debug core code for both TD webapp and TD desktop . Maybe later on today ... I will try :-)
