### ISSUE TITLE
Select and move multiple elements

### ISSUE THREAD

**Issue by p-** [mike-goodwin/owasp-threat-dragon-core#45]
Like the title says: it would be cool if selection and move of multiple elements would be supported.
(If it is supported: I'm sorry I couldn't figure out how 😉 )

**Comment by jgadsden** [comment]
Agreed that this enhancement would be great to have, and as fas as I know it is not yet supported. This has also been raised in the [owasp-threat-dragon repo](https://github.com/mike-goodwin/owasp-threat-dragon/issues/114) issue 114

**Comment by jgadsden** [comment]
Migrated to new issue in the OWASP area repo : https://github.com/OWASP/threat-dragon-core/issues/1
