### ISSUE TITLE
Enhancement: duplication of existing diagram and element

### ISSUE THREAD

**Issue by lmcthbe** [mike-goodwin/owasp-threat-dragon-core#50]
It would be useful to be able to duplicate existing diagram with threats within the same model as it is simpler to create multiple diagrams for each user story instead of having a single diagram (TD already supports multiple diagram creation in one model)

In the same spirit, it should also be useful to be able to duplicate existing element (process, store,..) with their threats from a diagram (via context menu ?) to speed up the modeling.

**Comment by jgadsden** [comment]
Agreed @lmcthbe , it would be very useful to be able to copy + paste diagram elements (along with their associated threats) within a diagram. In addition it would be great to duplicate whole diagrams within a project. 
I hesitate to suggest this workaround, but the threat model json can be edited 'in the raw' to do this diagram duplication ... not sure if you should try this at home though :-)

**Comment by lmcthbe** [comment]
I might be able to get a student internship to work on this as I really want to use TD as the main tool for the threat modeling in our secure development process for Q1 2020.

**Comment by jgadsden** [comment]
That would be great, thankyou @lmcthbe . Make sure you apply the fix for the trust boundary (and data flow) as this makes the tool much easier to use: #49

**Comment by lmcthbe** [comment]
I got a student internship. He gonna work 1 day for week for now and might be extended to two. We have decided to go with the web interface instead of the desktop application to have a centralized location for everyone, I guess that the fix will apply to both ? One question, we wanted to interface with GitLab instead of GitHub to store models, is the architecture flexible enough to handle it ?

**Comment by jgadsden** [comment]
Hello @lmcthbe - great news, thanks for doing this. If you apply changes to owasp-threat-dragon-core then these will be applied to both web interface and desktop versions.
I do not know about the GitLab vs GitHub question - over to @mike-goodwin on this one

**Comment by jgadsden** [comment]
Hello @andk123 , sorry to not be able to help with the login / welcome page that you are accessing. If this is still a problem could you raise it on the github.com/mike-goodwin/owasp-threat-dragon repo please?

**Comment by andk123** [comment]
Sure. I will give it another look and raise an issue if I still cannot access it. Thanks!
