### ISSUE TITLE
unable to Undo

### ISSUE THREAD

**Issue by securestep9** [mike-goodwin/owasp-threat-dragon-core#58]
Undo command is missing in Edit - it makes life very difficult when you accidentally delete something by mistake (Redo is needed as well)

**Comment by jgadsden** [comment]
Note that Undo/Redo is in the paid-for Rappid version of JointJS (along with zooming and panning) but obviously we stick with the open source JointJS version:
https://www.jointjs.com/rappid-comparison

**Comment by jgadsden** [comment]
Migrated to new issue in the OWASP area repo : https://github.com/OWASP/threat-dragon-core/issues/4
