### ISSUE TITLE
Enhancement request for copy paste text and Copy diagrams and threats

### ISSUE THREAD

**Issue by bc-venkata** [mike-goodwin/owasp-threat-dragon-core#59]
It is redundant work to type threat's description and mitigations. It'll be easy to copy threats over from place to other. And it'll be convenient to have copy and paste options to copy/paste text all around

**Comment by jgadsden** [comment]
Hello @bc-venkata - with the latest version 1.0 release you should now be able to copy and paste text:
https://github.com/mike-goodwin/owasp-threat-dragon-desktop/releases/tag/v1.0
The copy and paste of existing elements in the diagram, and also the diagrams themselves, is being worked on in issue #50 by @andk123 so we should have an update sometime soon
