### ISSUE TITLE
Scaling of icons behaves strangely after using the zoom function

### ISSUE THREAD

**Issue by meetinthemiddle-be** [mike-goodwin/owasp-threat-dragon-core#73]
See sccreenshot:

<img width="328" alt="Screenshot 2020-02-29 at 16 06 28" src="https://user-images.githubusercontent.com/26706067/75610132-c9b56700-5b0e-11ea-8e42-82d0a53839a1.png">

**Comment by jgadsden** [comment]
Hello @meetinthemiddle-be 
This issue is part of a larger problem with the zoom feature. For the moment we are removing zoom #94 and will reinstate it when zoom is working fully #95 . Thanks for raising this issue, and I hope it is OK to close your issue as it is now part of #95
