### ISSUE TITLE
Feature request: Clarify color

### ISSUE THREAD

**Issue by adamshostack** [mike-goodwin/owasp-threat-dragon-core#75]
The sample diagram has some elements (background worker, worker config, etc) which show in red.  It's not clear what red means.  (dashed lines seem to be used for both trust boundaries and Out of scope).

I suggest adding a key, but possibly alternately reducing use of color to address the threat of black & white printing.

**Comment by jgadsden** [comment]
Migrated to new issue in the OWASP area repo : https://github.com/OWASP/threat-dragon-core/issues/6
